#!/usr/bin/env python3
"""Turn confirmed candidates into dependency-ordered removal and annotation stories."""

from __future__ import annotations

import argparse
import heapq
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from xml.sax.saxutils import escape

from apex_common import (
    BLIND_SPOT_DISPLAY_NAMES, ContractError, attached_tests, cli_guard,
    default_data_dir, id_key, parse_bool, parse_int, qualified_name,
    is_self_match, outside_apex_callers, outside_string_holders, read_csv, read_table,
    safe_filename, tarjan, write_csv, write_json,
)
from apex_common import CATALOG_COLUMNS, CANDIDATE_EXTRA_COLUMNS, EDGE_COLUMNS, type_key
from capacity_triage import has_entry_point_signal, is_test_only


REASON_COLUMNS = ["verdict", "confidence", "bucket", "reasons", "quotes"]
DISPOSITION_COLUMNS = ["qualifiedName", "disposition", "decidedBy", "decidedOn", "note"]
PLANNER_STORY_MARKER = "<!-- generated by removal_plan.py -->"
# A class whose name or automation summary names a schedule may hold a pending scheduled job.
SCHEDULE_SIGNAL = re.compile(r"Schedul(?:able|ed|er)", re.IGNORECASE)
NAMESPACE_PREFIX = re.compile(r"[A-Za-z][A-Za-z0-9_]*\.")
FLOW_RULE_UNEVALUATED = "Flow trigger types were not in the bundle; the Flow referrer rule (scheduled, record-triggered or platform-event-triggered) was not evaluated for this unit"


def write_metadata_manifest(
    path: Path, members_by_type: dict[str, set[str]], *, version: str
) -> None:
    """Write one Salesforce Metadata API package manifest."""
    type_blocks = []
    for metadata_type, members in sorted(members_by_type.items()):
        if not members:
            continue
        member_lines = "\n".join(
            f"        <members>{escape(member)}</members>"
            for member in sorted(members)
        )
        type_blocks.append(
            f"    <types>\n{member_lines}\n"
            f"        <name>{escape(metadata_type)}</name>\n"
            "    </types>"
        )
    body = "\n".join(type_blocks)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<Package xmlns="http://soap.sforce.com/2006/04/metadata">\n'
        f"{body}\n"
        f"    <version>{escape(version)}</version>\n"
        "</Package>\n",
        encoding="utf-8",
    )


def metadata_api_type(display_type: str) -> str:
    """Map dependency display types to Metadata API manifest type names."""
    return "".join(display_type.split())


def render_blind_spot_value(value: object) -> str:
    if value is None:
        return "none"
    if isinstance(value, list):
        return ", ".join(render_blind_spot_value(item) for item in value) or "none"
    if isinstance(value, dict):
        return ", ".join(
            f"{key}: {render_blind_spot_value(nested)}"
            for key, nested in sorted(value.items())
        ) or "none"
    if isinstance(value, bool):
        return str(value).lower()
    return str(value)


def targeted_string_holder_result(
    name: str,
    rows: list[dict[str, str]],
    outside_holders: list[str],
    blocked_members: set[str],
    catalog_kinds: dict[str, str],
) -> str:
    test_holders = sorted({
        row["holderName"] for row in rows
        if parse_bool(row["holderIsTest"], field="holderIsTest")
        and row["holderName"]
    })
    blocked_set: set[str] = set()
    unblocked_set: set[str] = set()
    for row in rows:
        holder = row.get("holderName", "").strip()
        if holder not in outside_holders:
            continue
        if parse_bool(row.get("holderIsTest", ""), field="holderIsTest"):
            continue
        member_row = {
            "qualifiedName": holder,
            "holderName": holder,
            "holderType": row.get("holderType", ""),
        }
        if holder in blocked_members and is_self_match(member_row, catalog_kinds):
            blocked_set.add(holder)
        else:
            unblocked_set.add(holder)
    blocked_holders = sorted(blocked_set)
    if blocked_holders and not unblocked_set:
        result = (
            f"Targeted string search for {name}: "
            + "; ".join(
                f"held by {holder}, which stays; see its blocked reason"
                for holder in blocked_holders
            )
        )
    elif outside_holders:
        result = (
            f"Targeted string search for {name}: non-test holders outside the "
            f"removal set: {', '.join(outside_holders)}"
        )
    else:
        result = (
            f"Targeted string search for {name}: no non-test holders outside "
            "the removal set"
        )
    if test_holders:
        result += f"; test holders are exempt: {', '.join(test_holders)}"
    return result + "."


def plan_validation_results(
    tranches: list[dict[str, object]],
    graph: dict[str, set[str]],
    catalog_by_name: dict[str, dict[str, str]],
    capacity_totals: dict[str, object],
    q06_targets: set[str] | None = None,
) -> list[dict[str, object]]:
    """Compute order, survivor-reference, test, and capacity invariants."""
    flattened_units = [
        unit
        for tranche in tranches
        for unit in tranche.get("units", [])
        if isinstance(unit, dict)
    ]
    position = {
        str(member): index
        for index, unit in enumerate(flattened_units)
        for member in unit.get("members", [])
    }
    order_counterexamples = [
        {"consumer": source, "provider": target}
        for source, targets in graph.items()
        for target in targets
        if source in position and target in position
        and position[source] > position[target]
    ]

    attached = [
        str(test)
        for unit in flattened_units
        for test in unit.get("tests", [])
    ]
    attached_set = set(attached)
    removed = set(position)
    test_counterexamples: list[dict[str, object]] = []
    for test in sorted(attached_set):
        count = attached.count(test)
        if count != 1:
            test_counterexamples.append({"test": test, "placements": count})
        outside = {
            target
            for target in graph.get(test, set())
            if target in catalog_by_name
            and target not in attached_set
            and target not in removed
        }
        if outside:
            test_counterexamples.append({
                "test": test,
                "reachesOutsideRemovedUnits": sorted(outside),
            })

    precursor_targets: dict[str, set[str]] = defaultdict(set)
    for unit in flattened_units:
        for rewrite in unit.get("precursorRewrites", []):
            if not isinstance(rewrite, dict):
                continue
            survivor = str(rewrite.get("class", ""))
            if rewrite.get("kind") == "test-edit" and survivor:
                precursor_targets[survivor].update(
                    str(name) for name in rewrite.get("removeReferencesTo", [])
                )
    q06_targets = q06_targets or set()
    survivor_counterexamples: list[dict[str, object]] = []
    for survivor, row in sorted(catalog_by_name.items()):
        if survivor in removed or survivor in attached_set:
            continue
        references_removed = graph.get(survivor, set()) & removed
        if not references_removed:
            continue
        is_test = str(row.get("isTestClass", "")).strip().casefold() == "true"
        covered = precursor_targets.get(survivor, set()) if is_test else q06_targets
        missing = references_removed - covered
        if missing:
            survivor_counterexamples.append({
                "survivor": survivor,
                "referencesRemoved": sorted(missing),
            })

    precursor_counterexamples: list[dict[str, object]] = []
    for tranche in tranches:
        tranche_number = tranche.get("tranche")
        package_members = {
            str(name) for name in tranche.get("package", [])
        }
        stories_by_test: dict[str, list[dict[str, object]]] = defaultdict(list)
        for story in tranche.get("precursorStories", []):
            if isinstance(story, dict) and story.get("kind") == "test-edit":
                stories_by_test[str(story.get("class", ""))].append(story)
        rewrites_by_test: dict[str, set[str]] = defaultdict(set)
        for unit in tranche.get("units", []):
            if not isinstance(unit, dict):
                continue
            for rewrite in unit.get("precursorRewrites", []):
                if not isinstance(rewrite, dict) or rewrite.get("kind") != "test-edit":
                    continue
                test = str(rewrite.get("class", ""))
                rewrites_by_test[test].update(
                    str(name) for name in rewrite.get("removeReferencesTo", [])
                )
        for test, removed_names in sorted(rewrites_by_test.items()):
            if test not in package_members:
                precursor_counterexamples.append({
                    "test": test,
                    "tranche": tranche_number,
                    "missing": "package.xml",
                })
            stories = stories_by_test.get(test, [])
            if not stories:
                precursor_counterexamples.append({
                    "test": test,
                    "tranche": tranche_number,
                    "missing": "precursor story",
                })
            elif len(stories) != 1:
                precursor_counterexamples.append({
                    "test": test,
                    "tranche": tranche_number,
                    "precursorStoryPlacements": len(stories),
                })
            else:
                story_removed = {
                    str(name)
                    for name in stories[0].get("removeReferencesTo", [])
                }
                if story_removed != removed_names:
                    precursor_counterexamples.append({
                        "test": test,
                        "tranche": tranche_number,
                        "storyRemovedReferences": sorted(story_removed),
                        "expectedRemovedReferences": sorted(removed_names),
                    })

    expected_manifests = [
        [
            str(name)
            for unit in tranche.get("units", [])
            for name in [*unit.get("members", []), *unit.get("tests", [])]
        ]
        for tranche in tranches
    ]
    manifest_counterexamples = [
        {
            "tranche": tranche.get("tranche"),
            "manifest": tranche.get("manifest", []),
            "expected": expected,
        }
        for tranche, expected in zip(tranches, expected_manifests)
        if tranche.get("manifest", []) != expected
    ]
    manifest_names = [name for manifest in expected_manifests for name in manifest]
    manifest_characters = sum(
        parse_int(
            catalog_by_name[name].get("countedCharacters", ""),
            allow_empty=True,
            field=f"{name} countedCharacters",
        ) or 0
        for name in manifest_names
        if name in catalog_by_name
    )
    forecast_total = sum(
        int(capacity_totals.get(key, 0) or 0)
        for key in ("forecastReconciled", "unreconciledCandidate")
    )
    capacity_counterexamples = list(manifest_counterexamples)
    if manifest_characters != forecast_total:
        capacity_counterexamples.append({
            "manifestCharacters": manifest_characters,
            "forecastCharacters": forecast_total,
        })
    realized = capacity_totals.get("confirmedRealized")
    if realized is not None and realized != manifest_characters:
        capacity_counterexamples.append({
            "manifestCharacters": manifest_characters,
            "confirmedRealized": realized,
        })

    return [
        {
            "name": "consumer-before-provider",
            "passed": not order_counterexamples,
            "counterexamples": order_counterexamples,
        },
        {
            "name": "test-attachments",
            "passed": not test_counterexamples,
            "counterexamples": test_counterexamples,
        },
        {
            "name": "survivor-references",
            "passed": not survivor_counterexamples,
            "counterexamples": survivor_counterexamples,
        },
        {
            "name": "test-edit-precursors",
            "passed": not precursor_counterexamples,
            "counterexamples": precursor_counterexamples,
        },
        {
            "name": "capacity",
            "passed": not capacity_counterexamples,
            "counterexamples": capacity_counterexamples,
        },
    ]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dispositions", required=True, type=Path)
    parser.add_argument("--candidates", required=True, type=Path)
    parser.add_argument("--catalog", required=True, type=Path)
    parser.add_argument("--edges", required=True, type=Path)
    parser.add_argument("--edges-extra", type=Path)
    parser.add_argument("--reasoned", required=True, type=Path)
    parser.add_argument("--catalog-summary", type=Path)
    parser.add_argument(
        "--api-names", type=Path,
        help="JSON object mapping non-Apex parent node ids to API names",
    )
    parser.add_argument(
        "--string-holders", type=Path,
        help="targeted string-holder file written under work/triage",
    )
    parser.add_argument(
        "--string-search-unavailable", action="store_true",
        help="record that targeted string search was unavailable",
    )
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument("--stories-dir", required=True, type=Path)
    parser.add_argument("--data-dir", type=Path, default=default_data_dir(__file__))
    parser.add_argument("--allow-unevaluated-flow-rule", action="store_true")
    return parser


def run(args: argparse.Namespace) -> None:
    if args.string_holders and args.string_search_unavailable:
        raise ContractError(
            "pass either --string-holders or --string-search-unavailable, not both"
        )
    if not args.string_holders and not args.string_search_unavailable:
        raise ContractError(
            "pass --string-holders or --string-search-unavailable"
        )
    validation_path = args.out_dir / "validation.json"
    if validation_path.is_file():
        validation_path.unlink()
    for stale_name in ("coverage.json", "coverage-worksheet.csv"):
        stale_path = args.out_dir / stale_name
        if stale_path.is_file():
            stale_path.unlink()
    quarantine_rules = read_table(args.data_dir, "quarantine-rules.csv", ["rule", "condition", "story_kind"])
    review_reasons = read_table(args.data_dir, "review-first-reasons.csv", ["reason", "meaning", "rescue_signal"])
    thresholds = read_table(args.data_dir, "thresholds.csv", ["id", "name", "value", "unit", "how_computed", "who_sets", "used_by"])
    _, dispositions = read_csv(args.dispositions, DISPOSITION_COLUMNS)
    _, candidates = read_csv(args.candidates, CATALOG_COLUMNS + CANDIDATE_EXTRA_COLUMNS)
    _, catalog = read_csv(args.catalog, CATALOG_COLUMNS)
    edge_fields, edge_rows = read_csv(args.edges, EDGE_COLUMNS)
    edge_inputs = [
        (edge, "MetadataComponentTriggerType" in edge_fields)
        for edge in edge_rows
    ]
    if args.edges_extra:
        extra_fields, extra = read_csv(args.edges_extra, EDGE_COLUMNS[:8])
        edge_inputs.extend(
            (edge, "MetadataComponentTriggerType" in extra_fields)
            for edge in extra
        )
    _, reasoned = read_csv(args.reasoned, CATALOG_COLUMNS + CANDIDATE_EXTRA_COLUMNS + REASON_COLUMNS)
    catalog_by_name = {row["qualifiedName"]: row for row in catalog}
    catalog_kinds = {name: row["kind"] for name, row in catalog_by_name.items()}
    catalog_by_fold = {name.casefold(): row for name, row in catalog_by_name.items()}
    catalog_by_id = {id_key(row["sfId"]): row for row in catalog if row["sfId"]}
    candidate_by_name = {row["qualifiedName"]: row for row in candidates}
    reasoned_by_name = {row["qualifiedName"]: row for row in reasoned}
    reason_meanings = {row["reason"]: row["meaning"] for row in review_reasons}
    api_names: dict[str, str] = {}
    if args.api_names:
        try:
            loaded_api_names = json.loads(args.api_names.read_text(encoding="utf-8"))
        except FileNotFoundError:
            raise ContractError(
                f"missing required API names file: {args.api_names}"
            ) from None
        except json.JSONDecodeError as exc:
            raise ContractError(
                f"invalid API names JSON {args.api_names}: {exc.msg}"
            ) from None
        if not isinstance(loaded_api_names, dict):
            raise ContractError("API names file must be a JSON object")
        for node_id, value in loaded_api_names.items():
            if (
                not isinstance(node_id, str)
                or not isinstance(value, dict)
                or not isinstance(value.get("apiName"), str)
                or not value["apiName"].strip()
            ):
                raise ContractError(
                    "each API names entry must map a node id to a non-empty apiName"
                )
            api_names[node_id] = value["apiName"].strip()

    telemetry_threshold = next((row for row in thresholds if row["id"] == "T-12"), None)
    if not telemetry_threshold:
        raise ContractError("missing threshold T-12 in thresholds.csv")
    minimum_held_days = parse_int(telemetry_threshold["value"], field="T-12 value")

    ledger_path = args.candidates.parent / "telemetry-ledger.json"
    try:
        telemetry_ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ContractError(f"missing required telemetry ledger file: {ledger_path}") from None
    except json.JSONDecodeError as exc:
        raise ContractError(f"invalid telemetry ledger JSON: {exc.msg}") from None
    if not isinstance(telemetry_ledger, dict):
        raise ContractError("telemetry ledger must be a JSON object")
    effective_days = telemetry_ledger.get("effectiveDays")
    requested_days = telemetry_ledger.get("requestedDays")
    provisional_present = "provisional" in telemetry_ledger
    provisional_value = telemetry_ledger.get("provisional")
    if provisional_present and type(provisional_value) is not bool:
        raise ContractError("telemetry ledger provisional must be a JSON boolean")
    is_provisional = provisional_value is True or (
        type(effective_days) is int and effective_days < minimum_held_days
    )
    if is_provisional:
        if type(effective_days) is not int or type(requested_days) is not int:
            raise ContractError("provisional telemetry effectiveDays and requestedDays must be JSON integers")
        raise ContractError(
            f"the bundle is provisional ({effective_days} of {requested_days} effective days); "
            f"the playbook blocks below {minimum_held_days} held days; obtain a sufficient bundle"
        )

    verdict_wording = {
        "observed_used_direct": "observed running",
        "observed_root_reachable": "reachable from code observed running",
        "live_root_unobserved": "reachable from a live entry point that was not observed",
        "test_only_reachable": "reachable only from test code",
        "dormant_candidate": "no evidence of use in the telemetry window",
        "unknown": "could not be established",
    }
    story_kind_wording = {
        "needs-rewrite": "needs a rewrite before removal",
        "precursor-rewrite": "a caller must be rewritten first",
    }

    schedule_liveness_names: set[str] = set()
    schedule_path = args.candidates.parent / "schedule-liveness.csv"
    if schedule_path.is_file():
        _, schedule_rows = read_csv(schedule_path, required=["qualifiedName"])
        schedule_liveness_names = {
            row["qualifiedName"] for row in schedule_rows if row["qualifiedName"]
        }

    disposition_by_name: dict[str, str] = {}
    for row in dispositions:
        if row["disposition"] not in {"remove", "keep", "decide-later", "annotate"}:
            raise ContractError(f"invalid disposition for {row['qualifiedName']}: {row['disposition']!r}")
        disposition_by_name[row["qualifiedName"]] = row["disposition"]
    note_by_name = {
        row["qualifiedName"]: row["note"].strip()
        for row in dispositions
        if row.get("note", "").strip()
    }
    requested_remove = {name for name, disposition in disposition_by_name.items() if disposition == "remove"}
    requested_annotate = {name for name, disposition in disposition_by_name.items() if disposition == "annotate"}
    missing_candidates = (requested_remove | requested_annotate) - set(candidate_by_name)
    if missing_candidates:
        raise ContractError(f"confirmed disposition(s) absent from candidates: {', '.join(sorted(missing_candidates))}")
    for name in sorted(requested_annotate):
        row = candidate_by_name[name]
        if not is_test_only(row) or has_entry_point_signal(row, schedule_liveness_names):
            raise ContractError(
                f"annotate is only valid for a test-only class with no entry-point signal: {name}"
            )
    confirmed = requested_remove

    graph: dict[str, set[str]] = {name: set() for name in catalog_by_name}
    incoming: dict[str, set[str]] = defaultdict(set)
    endpoint_types: dict[str, str] = {}
    incoming_non_apex: dict[str, list[dict[str, str]]] = defaultdict(list)
    unevaluated_flow_targets: set[str] = set()
    unevaluated_automation_referrers: dict[str, list[tuple[str, str]]] = defaultdict(list)
    pairs: set[tuple[str, str]] = set()
    for edge, flow_trigger_column_present in edge_inputs:
        endpoints: list[str] = []
        for prefix in ("", "Ref"):
            component_type = edge[f"{prefix}MetadataComponentType"]
            if type_key(component_type) not in {"apexclass", "apextrigger"}:
                endpoints.append(f"{component_type}:{qualified_name(edge[f'{prefix}MetadataComponentNamespace'], edge[f'{prefix}MetadataComponentName'])}")
                continue
            component_id = edge[f"{prefix}MetadataComponentId"]
            qname = qualified_name(edge[f"{prefix}MetadataComponentNamespace"], edge[f"{prefix}MetadataComponentName"])
            row = catalog_by_id.get(id_key(component_id)) or catalog_by_fold.get(qname.casefold())
            endpoints.append(row["qualifiedName"] if row else qname)
        pairs.add((endpoints[0], endpoints[1]))
        endpoint_types[endpoints[0]] = edge["MetadataComponentType"]
        endpoint_types[endpoints[1]] = edge["RefMetadataComponentType"]
        source_type = edge["MetadataComponentType"]
        if (
            type_key(source_type) not in {"apexclass", "apextrigger"}
            and endpoints[1] in catalog_by_name
        ):
            raw_trigger_type = edge.get("MetadataComponentTriggerType", "").strip()
            if raw_trigger_type == "Scheduled":
                trigger_type = "scheduled"
            elif raw_trigger_type.startswith("Record"):
                trigger_type = "recordtriggered"
            elif raw_trigger_type == "PlatformEvent":
                trigger_type = "platformevent"
            else:
                trigger_type = ""
            source_type_key = type_key(source_type)
            if source_type_key == "flow" and not flow_trigger_column_present:
                unevaluated_flow_targets.add(endpoints[1])
            if source_type_key in {
                "processbuilderworkflow", "workflowrule",
            }:
                unevaluated_automation_referrers[endpoints[1]].append((
                    source_type, edge["MetadataComponentName"],
                ))
            incoming_non_apex[endpoints[1]].append({
                "type": source_type,
                "label": edge["MetadataComponentName"],
                "nodeId": edge.get("parentNodeId", ""),
                "apiName": api_names.get(edge.get("parentNodeId", ""), ""),
                "triggerType": trigger_type,
                "namespace": edge.get("MetadataComponentNamespace", "").strip(),
            })
    for source, target in pairs:
        graph.setdefault(source, set()).add(target)
        incoming[target].add(source)

    confirmed_sccs = tarjan(confirmed, graph)
    unevaluated_automation_targets = set(unevaluated_automation_referrers)
    unevaluated_targets = unevaluated_flow_targets | unevaluated_automation_targets
    unevaluated_units = sorted(
        min(component)
        for component in confirmed_sccs
        if component & unevaluated_targets
    )
    unevaluated_flow_units = sorted(
        min(component)
        for component in confirmed_sccs
        if component & unevaluated_flow_targets
    )
    unevaluated_flow_members = set().union(*(
        component
        for component in confirmed_sccs
        if component & unevaluated_flow_targets
    )) if unevaluated_flow_targets else set()
    unevaluated_rules = ([{
        "rule": "flow-trigger-block",
        "units": unevaluated_units,
    }] if unevaluated_units else [])
    if unevaluated_flow_units and not args.allow_unevaluated_flow_rule:
        raise ContractError(
            FLOW_RULE_UNEVALUATED + ": " + ", ".join(unevaluated_flow_units)
        )

    def outside_callers(name: str) -> list[str]:
        return outside_apex_callers(
            name,
            incoming=incoming,
            endpoint_types=endpoint_types,
            catalog_by_name=catalog_by_name,
            confirmed=confirmed,
        )

    targeted_holders: dict[str, list[dict[str, str]]] = defaultdict(list)
    if args.string_holders:
        _, holder_rows = read_csv(
            args.string_holders,
            required=[
                "qualifiedName", "holderName", "holderType", "holderIsTest",
                "holderInSelectedSet",
            ],
        )
        for holder in holder_rows:
            if holder["qualifiedName"] in candidate_by_name:
                targeted_holders[holder["qualifiedName"]].append(holder)

    def external_string_holders(name: str) -> list[str]:
        if args.string_holders:
            return outside_string_holders(targeted_holders.get(name, []), confirmed, kinds=catalog_kinds)
        return []

    def has_external_string_reference(name: str) -> bool:
        return bool(external_string_holders(name))

    for name in sorted(confirmed):
        if has_external_string_reference(name):
            external_string_holders(name)

    def quarantine_matches(rule: dict[str, str], name: str) -> bool:
        if rule["rule"] == "Q-04":
            return has_external_string_reference(name)
        if rule["rule"] == "Q-06":
            return bool(outside_callers(name))
        if rule["rule"] in {"Q-01", "Q-02", "Q-03", "Q-05", "Q-07"}:
            return False
        raise ContractError(
            f"unsupported quarantine rule in decision table: {rule['rule']}"
        )

    quarantine_rows: list[dict[str, str]] = []
    quarantine_story_kind: dict[tuple[str, str], str] = {}
    quarantine_rules_by_precedence = sorted(
        quarantine_rules,
        key=lambda rule: rule["rule"] != "Q-06",
    )
    for name in sorted(confirmed):
        for rule in quarantine_rules_by_precedence:
            if quarantine_matches(rule, name):
                if rule["rule"] == "Q-06":
                    callers = outside_callers(name)
                    evidence = f"outsideCallers={','.join(callers)}"
                elif rule["rule"] == "Q-04":
                    evidence = "holders=" + ",".join(external_string_holders(name))
                else:
                    evidence = rule["condition"]
                quarantine_rows.append({"qualifiedName": name, "rule": rule["rule"], "evidence": evidence})
                quarantine_story_kind[(name, rule["rule"])] = rule["story_kind"]
                break
    quarantined = {row["qualifiedName"] for row in quarantine_rows}

    cluster_threshold_row = next((row for row in thresholds if row["id"] == "T-6"), None)
    if not cluster_threshold_row:
        raise ContractError("missing threshold T-6 in thresholds.csv")
    cluster_threshold = parse_int(cluster_threshold_row["value"], field="T-6 value")
    modification_groups: dict[tuple[str, str], list[str]] = defaultdict(list)
    for row in candidates:
        stamp = row["lastModifiedDate"].strip()
        if stamp:
            modification_groups[(row["componentLabel"], stamp[:16])].append(row["qualifiedName"])
    modification_cluster: dict[str, tuple[int, str, str]] = {}
    for (component, minute), names in modification_groups.items():
        if len(names) >= cluster_threshold:
            for name in names:
                modification_cluster[name] = (len(names), component, minute)

    blocked_by_quarantine: dict[str, str] = {}
    for consumer in sorted(quarantined):
        pending_providers = list(graph.get(consumer, set()) & confirmed)
        seen_providers: set[str] = set()
        while pending_providers:
            provider = pending_providers.pop()
            if provider in seen_providers:
                continue
            seen_providers.add(provider)
            if provider not in quarantined:
                blocked_by_quarantine.setdefault(provider, f"downstream/provider of quarantined consumer {consumer}")
            pending_providers.extend((graph.get(provider, set()) & confirmed) - seen_providers)
    raw_units: list[set[str]] = []
    cycle_quarantine_blocked: dict[str, str] = {}
    for members in confirmed_sccs:
        quarantined_members = members & quarantined
        remaining_members = members - quarantined_members
        if not remaining_members:
            continue
        raw_units.append(remaining_members)
        if quarantined_members:
            reasons = [
                f"cycle member {name} is quarantined under {row['rule']}"
                for name in sorted(quarantined_members)
                for row in quarantine_rows
                if row["qualifiedName"] == name
            ]
            reason = "; ".join(reasons)
            for name in remaining_members:
                cycle_quarantine_blocked[name] = reason

    # Attach tests that can reach the unit through test-only edges and have no production target outside it.
    test_names = {row["qualifiedName"] for row in catalog if parse_bool(row["isTestClass"], field=f"{row['qualifiedName']} isTestClass")}

    units: list[dict[str, object]] = []
    for members in raw_units:
        attached = attached_tests(
            members,
            graph=graph,
            test_names=test_names,
            catalog_names=set(catalog_by_name),
        )
        character_values = [parse_int(catalog_by_name[name]["countedCharacters"], allow_empty=True, field=f"{name} countedCharacters") for name in members]
        if any(value is None for value in character_values):
            raise ContractError(f"cannot plan unit {min(members)}: countedCharacters is unknown")
        referrers = sorted(
            {
                (
                    item["type"], item["label"], item["triggerType"],
                    item["nodeId"], item["apiName"],
                )
                for name in members
                for item in incoming_non_apex.get(name, [])
            },
            key=lambda item: tuple(value.casefold() for value in item),
        )
        live_flows = [
            label for component_type, label, trigger_type, _, _ in referrers
            if type_key(component_type) == "flow"
            and trigger_type in {"scheduled", "recordtriggered", "platformevent"}
        ]
        flow_referrer_trigger_types = sorted({
            trigger_type for component_type, _, trigger_type, _, _ in referrers
            if type_key(component_type) == "flow" and trigger_type
        })
        manual_steps = [
            {
                "type": component_type,
                "label": label,
                "nodeId": node_id,
                "action": f"delete {label} in Setup",
            }
            for component_type, label, _, node_id, api_name in referrers
            if not api_name
            and type_key(component_type) not in {
                "processbuilderworkflow", "workflowrule",
            }
        ]
        units.append({
            "label": min(members), "members": sorted(members), "tests": attached,
            "countedCharacters": sum(value for value in character_values if value is not None),
            "destructiveChangesPost": [
                {"type": component_type, "name": api_name}
                for component_type, _, _, _, api_name in referrers
                if api_name
                if type_key(component_type) not in {
                    "processbuilderworkflow", "workflowrule",
                }
            ],
            "manualSteps": manual_steps,
            "liveFlowReferrers": live_flows,
            "flowReferrerTriggerTypes": flow_referrer_trigger_types,
            "unevaluatedAutomationReferrers": sorted({
                referrer
                for name in members
                for referrer in unevaluated_automation_referrers.get(name, [])
            }),
        })

    preblocked_units: list[dict[str, object]] = []
    active_units: list[dict[str, object]] = []
    for unit in units:
        cycle_reasons = sorted({
            cycle_quarantine_blocked[name]
            for name in unit["members"]
            if name in cycle_quarantine_blocked
        })
        if cycle_reasons:
            reasons = cycle_reasons
        else:
            reasons = sorted({
                blocked_by_quarantine[name]
                for name in unit["members"]
                if name in blocked_by_quarantine
            })
            reasons.extend(
                f"live Flow referrer {name}"
                for name in unit["liveFlowReferrers"]
            )
        reasons.extend(
            f"referenced by the {component_type} {name}; Elements cannot tell "
            "whether it runs, so this class stays until the process or rule is "
            "deactivated or confirmed unused"
            for component_type, name in unit["unevaluatedAutomationReferrers"]
        )
        if reasons:
            unit["blockedReason"] = "; ".join(reasons)
            preblocked_units.append(unit)
        else:
            active_units.append(unit)
    units = active_units

    # Consumers precede providers; among currently-ready SCCs, choose the biggest first.
    unit_for = {member: index for index, unit in enumerate(units) for member in unit["members"]}
    unit_graph: dict[int, set[int]] = {index: set() for index in range(len(units))}
    indegree = {index: 0 for index in range(len(units))}
    for source, target in pairs:
        left, right = unit_for.get(source), unit_for.get(target)
        if left is not None and right is not None and left != right and right not in unit_graph[left]:
            unit_graph[left].add(right)
            indegree[right] += 1
    ready = [
        (-int(units[index]["countedCharacters"]), str(units[index]["label"]).casefold(), index)
        for index, degree in indegree.items() if degree == 0
    ]
    heapq.heapify(ready)
    ordered_units: list[dict[str, object]] = []
    while ready:
        _, _, index = heapq.heappop(ready)
        ordered_units.append(units[index])
        for target in sorted(unit_graph[index]):
            indegree[target] -= 1
            if indegree[target] == 0:
                heapq.heappush(ready, (
                    -int(units[target]["countedCharacters"]),
                    str(units[target]["label"]).casefold(),
                    target,
                ))

    summary: dict[str, object] = {}
    if args.catalog_summary:
        try:
            loaded_summary = json.loads(args.catalog_summary.read_text(encoding="utf-8"))
        except FileNotFoundError:
            raise ContractError(f"missing required catalog summary file: {args.catalog_summary}") from None
        except json.JSONDecodeError as exc:
            raise ContractError(f"invalid catalog summary JSON {args.catalog_summary}: {exc.msg}") from None
        if not isinstance(loaded_summary, dict):
            raise ContractError(f"catalog summary must be a JSON object: {args.catalog_summary}")
        if "reconciled" not in loaded_summary:
            raise ContractError("catalog summary is missing required key: reconciled")
        if "reconciled" in loaded_summary and type(loaded_summary["reconciled"]) is not bool:
            raise ContractError("catalog summary reconciled must be a JSON boolean")
        summary = loaded_summary
    triage_summary_path = args.candidates.parent.parent / "triage" / "summary.json"
    triage_summary: dict[str, object] = {}
    if triage_summary_path.is_file():
        try:
            loaded_triage = json.loads(triage_summary_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ContractError(
                f"invalid triage summary JSON {triage_summary_path}: {exc.msg}"
            ) from None
        if not isinstance(loaded_triage, dict):
            raise ContractError(f"triage summary must be a JSON object: {triage_summary_path}")
        triage_summary = loaded_triage
    planned_units: list[dict[str, object]] = []
    skipped: list[dict[str, object]] = list(preblocked_units)
    surviving_consumers: dict[str, tuple[str, str]] = {
        member: (str(unit["blockedReason"]), str(unit["label"]))
        for unit in preblocked_units
        for member in unit["members"]
    }
    for unit in ordered_units:
        blocking_sources = sorted({source for member in unit["members"] for source in incoming.get(member, set()) if source in surviving_consumers})
        if blocking_sources:
            labels = ", ".join(sorted({
                surviving_consumers[source][1] for source in blocking_sources
            }))
            unit["blockedReason"] = (
                f"blocked because its consumer {labels} stays: Salesforce refuses to delete a referenced class"
            )
            skipped.append(unit)
            for member in unit["members"]:
                surviving_consumers[member] = (
                    str(unit["blockedReason"]), str(unit["label"])
                )
            continue
        planned_units.append(unit)

    attached_to_units = {
        test for unit in [*planned_units, *skipped] for test in unit["tests"]
    }
    surviving_tests = test_names - confirmed - attached_to_units
    for unit in [*planned_units, *skipped]:
        unit["precursorRewrites"] = [
            {
                "class": test,
                "kind": "test-edit",
                "removeReferencesTo": sorted(graph.get(test, set()) & set(unit["members"])),
            }
            for test in sorted(surviving_tests)
            if graph.get(test, set()) & set(unit["members"])
        ]

    tranche_groups: list[list[dict[str, object]]] = (
        [planned_units] if planned_units else []
    )

    placement_counts = {name: 0 for name in confirmed}
    for group in tranche_groups:
        for unit in group:
            for name in unit["members"]:
                placement_counts[name] += 1
    for row in quarantine_rows:
        placement_counts[row["qualifiedName"]] += 1
    for unit in skipped:
        for name in unit["members"]:
            placement_counts[name] += 1
    misplaced = {
        name: count for name, count in placement_counts.items() if count != 1
    }
    if misplaced:
        detail = ", ".join(
            f"{name}={count}" for name, count in sorted(misplaced.items())
        )
        raise ContractError(
            f"planner exactly-once output check failed for remove rulings: {detail}"
        )

    tranche_output: list[dict[str, object]] = []
    unit_plan: dict[str, dict[str, object]] = {}
    placed_members = {
        str(member)
        for group in tranche_groups
        for unit in group
        for member in unit["members"]
    }
    def blockers_for(members: list[str]) -> list[str]:
        blockers: set[str] = set()
        for name in members:
            row = catalog_by_name[name]
            if row["kind"] == "trigger":
                blockers.add(f"verify {name} trigger is Inactive before deletion")
            reasons = set(reasoned_by_name.get(name, {}).get("reasons", "").split(";"))
            if "sole_caller_of_executed_class" in reasons:
                blockers.add(
                    f"check Setup > Scheduled Jobs for {name}; if a job exists, "
                    "stop and re-rule before deletion"
                )
            elif row["scheduledJobNames"]:
                blockers.add(f"abort active schedules for {name} before deletion")
            elif SCHEDULE_SIGNAL.search(" ".join((
                name, candidate_by_name.get(name, {}).get("automationSummary", ""),
            ))):
                blockers.add(
                    f"check Setup > Scheduled Jobs for {name} and delete any pending "
                    "job before deletion, since a pending scheduled job blocks the delete"
                )
        return sorted(blockers)

    def recovery_prerequisites(members: list[str], tests: list[str]) -> list[str]:
        manifest = ", ".join(list(members) + list(tests))
        return [
            "capture an immutable backup location and checksum before deployment",
            f"record and verify the restore manifest before deployment: {manifest}",
        ]

    for tranche_number, group in enumerate(tranche_groups, start=1):
        manifest: list[str] = []
        rendered_units = []
        tranche_blockers: set[str] = set()
        for unit_position, unit in enumerate(group, start=1):
            manifest_start = len(manifest) + 1
            manifest.extend(unit["members"])
            manifest.extend(unit["tests"])
            unit_blockers = sorted(set(blockers_for(unit["members"])) | set(recovery_prerequisites(unit["members"], unit["tests"])))
            tranche_blockers.update(unit_blockers)
            rendered_units.append({"unit": unit["label"], "members": unit["members"], "tests": unit["tests"],
                                   "countedCharacters": unit["countedCharacters"], "quarantined": False,
                                   "precursorRewrites": unit["precursorRewrites"],
                                   "destructiveChangesPost": unit["destructiveChangesPost"],
                                   "manualSteps": unit["manualSteps"],
                                   "flowReferrerTriggerTypes": unit["flowReferrerTriggerTypes"]})
            unit_plan[str(unit["label"])] = {
                "tranche": tranche_number, "unitPosition": unit_position,
                "manifestStart": manifest_start, "manifest": list(unit["members"]) + list(unit["tests"]),
                "blockers": unit_blockers,
                "precursorRewrites": unit["precursorRewrites"],
                "destructiveChangesPost": unit["destructiveChangesPost"],
                "manualSteps": unit["manualSteps"],
            }
        precursor_by_test: dict[str, dict[str, object]] = {}
        for unit in group:
            for rewrite in unit["precursorRewrites"]:
                test = str(rewrite["class"])
                record = precursor_by_test.setdefault(test, {
                    "class": test,
                    "kind": "test-edit",
                    "removeReferencesTo": set(),
                    "keepReferencesTo": sorted(
                        graph.get(test, set())
                        & set(catalog_by_name)
                        - placed_members
                    ),
                })
                record["removeReferencesTo"].update(rewrite["removeReferencesTo"])
        precursor_stories = [
            {
                **record,
                "removeReferencesTo": sorted(record["removeReferencesTo"]),
            }
            for _, record in sorted(precursor_by_test.items())
        ]
        package_members = sorted(precursor_by_test)
        tranche_output.append({
            "tranche": tranche_number,
            "units": rendered_units,
            "operationalBlockers": sorted(tranche_blockers),
            "manifest": manifest,
            "package": package_members,
            "precursorStories": precursor_stories,
        })

        tranche_dir = args.out_dir / f"tranche-{tranche_number:02d}"
        api_versions = [
            float(row["apiVersion"])
            for row in catalog
            if row.get("apiVersion", "").strip()
        ]
        manifest_version = (
            f"{max(api_versions):.1f}" if api_versions else "65.0"
        )
        write_metadata_manifest(
            tranche_dir / "package.xml",
            {"ApexClass": set(package_members)},
            version=manifest_version,
        )
        destructive_members: dict[str, set[str]] = defaultdict(set)
        for unit in rendered_units:
            for name in [*unit["members"], *unit["tests"]]:
                kind = catalog_by_name[str(name)]["kind"]
                destructive_members[
                    "ApexTrigger" if kind == "trigger" else "ApexClass"
                ].add(str(name))
            for referrer in unit["destructiveChangesPost"]:
                destructive_members[
                    metadata_api_type(str(referrer["type"]))
                ].add(str(referrer["name"]))
        write_metadata_manifest(
            tranche_dir / "destructiveChangesPost.xml",
            destructive_members,
            version=manifest_version,
        )

    blocked_units = [
        {
            "unit": unit["label"],
            "members": unit["members"],
            "tests": unit["tests"],
            "countedCharacters": unit["countedCharacters"],
            "blockedReason": unit["blockedReason"],
            "precursorRewrites": unit["precursorRewrites"],
            "destructiveChangesPost": unit["destructiveChangesPost"],
            "manualSteps": unit["manualSteps"],
            "flowReferrerTriggerTypes": unit["flowReferrerTriggerTypes"],
        }
        for unit in skipped
    ]
    write_json(args.out_dir / "tranches.json", {
        "tranches": tranche_output,
        "blockedUnits": blocked_units,
        "unevaluatedRules": unevaluated_rules,
    })
    write_csv(args.out_dir / "quarantine.csv", ["qualifiedName", "rule", "evidence"], quarantine_rows)
    deletion_forecast = sum(
        int(unit["countedCharacters"])
        for group in tranche_groups for unit in group
    )
    annotation_forecast = sum(
        parse_int(
            candidate_by_name[name]["countedCharacters"],
            field=f"{name} countedCharacters",
        )
        for name in requested_annotate
    )
    forecast = deletion_forecast + annotation_forecast
    reconciled = bool(summary.get("reconciled")) if summary else False
    capacity_totals = {
        "forecastReconciled": deletion_forecast if reconciled else 0,
        "unreconciledCandidate": 0 if reconciled else deletion_forecast,
        "annotationForecast": annotation_forecast,
        "confirmedRealized": None,
    }
    write_json(args.out_dir / "capacity-totals.json", capacity_totals)
    computed_invariants = plan_validation_results(
        tranche_output, graph, catalog_by_name, capacity_totals,
        {row["qualifiedName"] for row in quarantine_rows if row["rule"] == "Q-06"},
    )
    invariants = [
        {"name": "placement", "passed": not misplaced, "counterexamples": []},
        *computed_invariants,
    ]
    all_counterexamples = [
        {"invariant": invariant["name"], **counterexample}
        for invariant in invariants
        for counterexample in invariant["counterexamples"]
    ]
    validation = {
        "status": "complete" if all(item["passed"] for item in invariants) else "failed",
        "counts": {
            "confirmedCandidates": len(confirmed),
            "annotationCandidates": len(requested_annotate),
            "tranches": len(tranche_output),
            "plannedUnits": sum(len(tranche["units"]) for tranche in tranche_output),
            "blockedUnits": len(blocked_units),
            "quarantineRows": len(quarantine_rows),
            "stories": 0,
        },
        "invariants": invariants,
        "counterexamples": all_counterexamples,
        "manualSteps": sorted(
            (
                step
                for tranche in tranche_output
                for unit in tranche["units"]
                for step in unit["manualSteps"]
            ),
            key=lambda step: (
                str(step["type"]).casefold(), str(step["label"]).casefold()
            ),
        ),
    }

    def optional_object(name: str) -> dict[str, object] | None:
        path = args.candidates.parent / name
        if not path.is_file():
            return None
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ContractError(f"invalid inferred {name} JSON: {exc.msg}") from None
        if not isinstance(value, dict):
            raise ContractError(f"inferred {name} must be a JSON object")
        return value

    blind_spots = optional_object("blind-spots.json")
    if blind_spots:
        blind_spots = {
            key: value for key, value in blind_spots.items()
            if "coverage" not in key.casefold()
            and not (args.string_holders and key.casefold() == "stringevidence")
        }
    if (
        args.string_search_unavailable
        or triage_summary.get("stringSearch") == "unavailable"
    ):
        blind_spots = {
            **(blind_spots or {}),
            "stringSearchUnavailable": "unavailable",
        }

    def targeted_string_result(name: str) -> str:
        rows = targeted_holders.get(name, [])
        outside_holders = outside_string_holders(rows, placed_removals, kinds=catalog_kinds)
        blocked_members = {
            str(member)
            for unit in blocked_units
            for member in unit["members"]
        }
        return targeted_string_holder_result(
            name, rows, outside_holders, blocked_members, catalog_kinds,
        )

    def absent_telemetry_result() -> str:
        types_absent = telemetry_ledger.get("typesAbsent", [])
        if not isinstance(types_absent, list) or not types_absent:
            return ""
        return (
            "Not watched in the window: "
            + ", ".join(str(name) for name in types_absent)
            + "; a class run only that way would look unused."
        )

    placed_removals = {
        member
        for group in tranche_groups
        for unit in group
        for member in unit["members"]
    }

    def orphaned_survivors(members: list[str]) -> list[str]:
        member_set = set(members)
        result = []
        for survivor, row in catalog_by_name.items():
            if survivor in placed_removals or row.get("kind") != "class":
                continue
            callers = {
                source for source in incoming.get(survivor, set())
                if source in catalog_by_name
                and catalog_by_name[source].get("kind") in {"class", "trigger"}
                and not parse_bool(
                    catalog_by_name[source]["isTestClass"],
                    field=f"{source} isTestClass",
                )
            }
            if callers and callers <= placed_removals and callers & member_set:
                result.append(survivor)
        return sorted(result)

    def story_text(title: str, members: list[str], tests: list[str], characters: int,
                   plan_record: dict[str, object] | None, extra_evidence: str,
                   behavior_impact: str, blockers: list[str] | None = None,
                   pending_rewrites: list[dict[str, object]] | None = None) -> str:
        identities = [f"- {name}: Salesforce Id `{catalog_by_name[name]['sfId']}`" for name in members if name in catalog_by_name]
        identities.extend(f"- Test: {name}: Salesforce Id `{catalog_by_name[name]['sfId']}`" for name in tests if name in catalog_by_name)
        zero = ", ".join(tests) or "None"
        evidence_lines = []
        for name in members:
            row = reasoned_by_name.get(name)
            if row:
                meanings = [reason_meanings.get(reason, reason.replace("_", " ")) for reason in row["reasons"].split(";") if reason]
                confidence = "high" if row["confidence"].casefold().startswith("high") else "medium"
                evidence_lines.append(
                    f"- {name}: Evidence: {verdict_wording.get(row['verdict'], verdict_wording['unknown'])} "
                    f"(confidence {confidence}). Reasons for doubt: {'; '.join(meanings) or 'none'}. "
                    f"Supporting evidence: {row['quotes'] or 'none'}."
                )
            else:
                evidence_lines.append(f"- {name}: no reasoned-candidates row available")
        evidence_lines.append(f"- Additional evidence: {extra_evidence}")
        cluster_details = {
            modification_cluster[name]
            for name in members
            if name in modification_cluster
        }
        for count, component, minute in sorted(cluster_details, key=lambda value: (value[1], value[2])):
            evidence_lines.append(
                f"- Modification cluster: {count} component members share lastModifiedDate minute "
                f"{minute} in {component}; this is treated as one deployment event."
            )
        if telemetry_ledger:
            evidence_lines.append(f"- Telemetry window: {telemetry_ledger.get('windowStart', 'unknown')} through {telemetry_ledger.get('windowEnd', 'unknown')}")
        else:
            evidence_lines.append("- Telemetry window: unavailable; telemetry-ledger.json was not present beside candidates.csv")
        absent_telemetry = absent_telemetry_result()
        if absent_telemetry:
            evidence_lines.append(f"- {absent_telemetry}")
        if args.string_holders:
            evidence_lines.extend(
                f"- {targeted_string_result(name)}" for name in members
            )
        if blind_spots:
            rendered_blind_spots = []
            for key in sorted(blind_spots):
                value = blind_spots[key]
                rendered_value = render_blind_spot_value(value)
                rendered_blind_spots.append(
                    f"{BLIND_SPOT_DISPLAY_NAMES.get(key, key)}: {rendered_value}"
                )
            evidence_lines.append(f"- Available blind spots: {'; '.join(rendered_blind_spots)}")
        else:
            evidence_lines.append("- Available blind spots: unavailable; blind-spots.json was not present beside candidates.csv")
        if set(members) & unevaluated_flow_members:
            evidence_lines[-1] += "; " + FLOW_RULE_UNEVALUATED

        unevaluated_referrer_sources = {
            f"{item['type']}:{item['label']}"
            for name in members
            for item in incoming_non_apex.get(name, [])
            if type_key(str(item["type"])) in {
                "processbuilderworkflow", "workflowrule",
            }
        }
        incoming_edges = sorted(
            (source, target)
            for target in members
            for source in incoming.get(target, set())
            if source not in unevaluated_referrer_sources
        )
        incoming_lines = [f"- `{source}` -> `{target}`" for source, target in incoming_edges] or ["- None at planning time."]
        story_referrers = sorted(
            {
                (str(referrer["type"]), str(referrer["name"]))
                for referrer in (
                    plan_record.get("destructiveChangesPost", [])
                    if plan_record else []
                )
            },
            key=lambda item: (item[0].casefold(), item[1].casefold()),
        )
        referrer_lines = "\n".join(
            f"- {component_type}: {name}"
            for component_type, name in story_referrers
        )
        precursor_rewrites = (
            plan_record.get("precursorRewrites", []) if plan_record else []
        )
        test_edit_lines = "\n".join(
            f"- Apex test class {rewrite['class']}: edit to remove references to "
            f"{', '.join(rewrite['removeReferencesTo'])}."
            for rewrite in precursor_rewrites
        )
        referrer_lines = referrer_lines or "- None."
        test_edit_section = (
            "\n\nSurviving tests edited in the same deployment (`package.xml`):\n\n"
            f"{test_edit_lines}"
            if test_edit_lines else ""
        )
        pending_rewrite_lines = "\n".join(
            f"- Once unblocked, {rewrite['class']} must stop referencing "
            f"{', '.join(rewrite['removeReferencesTo'])}."
            for rewrite in (pending_rewrites or [])
        )
        if pending_rewrite_lines:
            pending_rewrite_lines = (
                "\n\nSurviving tests edited in the same deployment (`package.xml`):\n\n"
                + pending_rewrite_lines
            )
        referrer_safety_lines = "\n".join(
            (
                f"Deactivate {component_type} {name} in Setup before deleting "
                "the Apex class."
                if type_key(component_type) in {
                    "processbuilderworkflow", "workflowrule",
                }
                else
                f"Before deleting {component_type} {name}, remove it from every page "
                "that uses it or deactivate it; the bundle does not include dependencies "
                "into this referrer."
            )
            for component_type, name in story_referrers
        )
        automation_referrers = sorted({
            (str(item["type"]), str(item["label"]))
            for name in members
            for item in incoming_non_apex.get(name, [])
            if type_key(str(item["type"])) in {
                "processbuilderworkflow", "workflowrule",
            }
            and not item["namespace"]
            and not NAMESPACE_PREFIX.match(str(item["apiName"] or item["label"]))
        })
        referrer_safety_lines = "\n\n".join(
            line for line in (
                referrer_safety_lines,
                *(
                    f"Deactivating {component_type} {name} is not enough; delete its "
                    "inactive versions too, since any flow version referencing the "
                    "class blocks the delete."
                    for component_type, name in automation_referrers
                ),
            ) if line
        )
        manual_step_lines = "\n".join(
            f"Manual Setup step: {step['action']}."
            for step in (plan_record.get("manualSteps", []) if plan_record else [])
        )
        if plan_record:
            step_lines = (
                f"Manifest position: tranche {plan_record['tranche']}, unit {plan_record['unitPosition']}.\n\n"
                f"Exact unit manifest: {', '.join(plan_record['manifest'])}.\n\n"
                f"The units in tranche {plan_record['tranche']} deploy atomically as one deployment; "
                "the manifest lists members alphabetically, an order with no meaning.\n\n"
                "Salesforce refuses to delete a referenced class, so each referrer lands in the same atomic deployment.\n\n"
                "Referrers removed in the same deployment (`destructiveChangesPost`):\n\n"
                f"{referrer_lines}{test_edit_section}\n\n"
                "Put the removed Apex members, attached tests, and non-Apex referrers in "
                "`destructiveChangesPost.xml`. Put edited surviving tests in `package.xml`; "
                "deploy both files as one atomic deployment."
            )
        else:
            step_lines = (
                "Manifest position: none until the dependency or rewrite blocker is cleared. "
                "No deletion manifest is authorized.\n\n"
                "Salesforce refuses to delete a referenced class, so each referrer lands in "
                "the same atomic deployment.\n\n"
                "Referrers removed in the same deployment "
                "(`destructiveChangesPost`):\n\n"
                f"{referrer_lines}{pending_rewrite_lines}"
            )
        blockers = blockers if blockers is not None else blockers_for(members)
        blockers = sorted(set(blockers) | set(recovery_prerequisites(members, tests)))
        blocker_text = "; ".join(blockers)
        restore_manifest = ", ".join(list(members) + list(tests)) or "no deletion metadata"
        production_deletion = (
            "Production Apex has no Delete in Setup; removal is a Metadata Application Programming "
            "Interface (API) deployment with a destructive-changes manifest, which runs local tests. "
            "Routes are Salesforce Command Line Interface (CLI) "
            "(`sf project deploy start --manifest package.xml "
            "--post-destructive-changes destructiveChangesPost.xml "
            "--test-level RunLocalTests "
            "--dry-run`) for validate-only, a Workbench zip, or the customer's own pipeline; "
            "change sets cannot delete Apex."
        )
        impact_lines = [f"Behavior impact: {behavior_impact}"]
        impact_lines.extend(
            f"Deleted in the same deployment: {component_type} {name}."
            for component_type, name in story_referrers
        )
        orphaned = orphaned_survivors(members)
        impact_lines.extend(
            f"Left with no caller after this removal: {name}." for name in orphaned
        )
        if not orphaned:
            impact_lines.append("Left with no caller after this removal: none.")
        impact_lines.extend(
            f"Surviving test edits in this deployment: {rewrite['class']} stops "
            f"referencing {', '.join(rewrite['removeReferencesTo'])}."
            for rewrite in precursor_rewrites
        )
        if not precursor_rewrites:
            impact_lines.append("Surviving test edits in this deployment: none.")
        reviewer_notes = "".join(
            f"\n\nReviewer's note on {name}: {note_by_name[name].rstrip('.')}."
            for name in members
            if name in note_by_name
        )
        return f"""# {title}

{PLANNER_STORY_MARKER}

## Identity

{chr(10).join(identities) or '- No deletable metadata in this rewrite story.'}

## Capacity reclaimed

{characters} counted characters. Zero-reclaim test classes: {zero}.

## Evidence

{chr(10).join(evidence_lines)}

## Impact

Incoming edges at planning time:

{chr(10).join(incoming_lines)}

{chr(10).join(impact_lines)}

## Steps

{step_lines}

{referrer_safety_lines}

{manual_step_lines}

{production_deletion}

Operational blockers: {blocker_text}

## Verification

The bundle carries no declared-root or access facts, so these are confirmed by the reviewer from the class source.

- not global and not @NamespaceAccessible
- no @RestResource and no webservice method
- not an interface, abstract class or Callable implementation
- no guest profile or guest permission set grants class access
- does not implement UninstallHandler

Run a validate-only deployment of the exact manifest with `RunLocalTests`; do not ignore errors. Roll back on any error. A later metadata change invalidates this validation.

## Recovery packet

- Backup location: NOT CAPTURED; deployment blocked
- Backup checksum: NOT CAPTURED; deployment blocked
- Restore manifest: {restore_manifest}
- Recovery time: NOT GUARANTEED; forward validate/deploy duration cannot be guaranteed

Deletion is irreversible; recovery is a forward deployment through the same gates.

## Advice for review-first items

Where a reversible switch exists (trigger Inactive, schedule aborted, or class access revoked), use it for one customer-defined business cycle before deleting.{reviewer_notes}
"""

    def test_edit_story_text(
        tranche_number: int, rewrite: dict[str, object]
    ) -> str:
        test = str(rewrite["class"])
        removed = [str(name) for name in rewrite["removeReferencesTo"]]
        kept = [str(name) for name in rewrite["keepReferencesTo"]]
        title_units = (
            removed[0]
            if len(removed) == 1
            else ", ".join(removed[:-1]) + f" and {removed[-1]}"
        )
        kept_text = ", ".join(kept) if kept else "None"
        return f"""# Rewrite {test} so {title_units} can be removed

{PLANNER_STORY_MARKER}

## Identity

- Apex test class {test}: Salesforce Id `{catalog_by_name[test]['sfId']}`

## Capacity reclaimed

0 counted characters. This story edits a surviving test class.

## Evidence

The test directly references {title_units}, removed in tranche {tranche_number}.

## Impact

Stop referencing removed classes: {', '.join(removed)}.

Keep referencing surviving classes: {kept_text}.

## Steps

Edit {test}, preserving its tested behavior for the surviving classes. Put the edited source in the Salesforce project and list `{test}` in tranche {tranche_number}'s `package.xml`.

Validate the edit and deletions together from the tranche directory:

`sf project deploy start --manifest package.xml --post-destructive-changes destructiveChangesPost.xml --test-level RunLocalTests --dry-run`

## Verification

Confirm the edited test compiles without the removed classes and that all local tests pass in the validate-only deployment.

## Recovery packet

Restore the prior test source only together with the removed classes it references.

## Advice for review-first items

Deploy the test edit and the deletions as one atomic deployment.
"""

    args.stories_dir.mkdir(parents=True, exist_ok=True)
    story_specs: list[tuple[str, str]] = []
    for tranche, group in zip(tranche_output, tranche_groups):
        for unit in group:
            story_specs.append((str(unit["label"]), story_text(
                f"Remove {unit['label']}", unit["members"], unit["tests"], int(unit["countedCharacters"]),
                unit_plan[str(unit["label"])],
                "confirmed removal disposition and dependency closure", "the listed classes and their behavior are removed; attached tests are removed without inflating reclaimed capacity",
                list(unit_plan[str(unit["label"])]["blockers"]),
            )))
        for rewrite in tranche["precursorStories"]:
            story_specs.append((
                f"rewrite-{rewrite['class']}",
                test_edit_story_text(int(tranche["tranche"]), rewrite),
            ))
    for unit in skipped:
        blocked_reason = str(unit.get("blockedReason", "dependency planning blocked this unit"))
        story_specs.append((str(unit["label"]), story_text(
            f"Remove {unit['label']}", unit["members"], unit["tests"], int(unit["countedCharacters"]),
            None, blocked_reason, "no behavior changes because no deletion manifest was produced",
            [blocked_reason, *blockers_for(list(unit["members"]))],
            pending_rewrites=list(unit["precursorRewrites"]),
        )))

    for name in sorted(requested_annotate):
        row = candidate_by_name[name]
        characters = parse_int(
            row["countedCharacters"], field=f"{name} countedCharacters"
        )
        annotation_evidence = [
            "- Only test classes call this class, and it has no entry-point signal.",
            f"- Telemetry window: {telemetry_ledger.get('windowStart', 'unknown')} "
            f"through {telemetry_ledger.get('windowEnd', 'unknown')}.",
        ]
        absent_telemetry = absent_telemetry_result()
        if absent_telemetry:
            annotation_evidence.append(f"- {absent_telemetry}")
        if args.string_holders:
            annotation_evidence.append(f"- {targeted_string_result(name)}")
        story_specs.append((f"annotate-{name}", f"""# Annotate {name} as @isTest

{PLANNER_STORY_MARKER}

## Identity

- {name}: Salesforce Id `{catalog_by_name[name]['sfId']}`

## Capacity reclaimed

{characters} counted characters.

## Evidence

{chr(10).join(annotation_evidence)}

## Impact

Marking the class `@isTest` excludes its characters from the org allocation; nothing is deleted.

## Steps

Add `@isTest` to the class declaration and deploy the source change through the customer's normal pipeline.

## Verification

Run the class's tests, then refresh the unused Apex bundle and confirm that its characters stop counting.

## Recovery packet

Remove the `@isTest` annotation and redeploy the prior source if the class must return to production use.

## Advice for review-first items

Confirm with the code owner that the class is a test factory before changing its annotation.
"""))
    quarantine_by_name: dict[str, list[dict[str, str]]] = defaultdict(list)
    for quarantine in quarantine_rows:
        quarantine_by_name[quarantine["qualifiedName"]].append(quarantine)
    for name in sorted(quarantine_by_name):
        rows = quarantine_by_name[name]
        precursor_rows = [row for row in rows if quarantine_story_kind[(name, row["rule"])] == "precursor-rewrite"]
        rewrite_rows = [row for row in rows if quarantine_story_kind[(name, row["rule"])] != "precursor-rewrite"]
        tests = attached_tests(
            {name},
            graph=graph,
            test_names=test_names,
            catalog_names=set(catalog_by_name),
        )
        for quarantine in precursor_rows:
            callers = outside_callers(name) or ["caller"]
            for caller in callers:
                label = f"{caller}-so-{name}"
                story_specs.append((label, story_text(
                    f"Rewrite {caller} so {name} can be removed", [name], tests,
                    int(parse_int(catalog_by_name[name]["countedCharacters"], field=f"{name} countedCharacters")),
                    None, f"{story_kind_wording[quarantine_story_kind[(name, quarantine['rule'])]]} ({quarantine['rule']}): {caller} -> {name}",
                    f"rewrite {caller} to remove its dependency on {name}; deletion remains prohibited until that rewrite is deployed", [f"surviving caller {caller}"],
                )))
        q04_rows = [row for row in rewrite_rows if row["rule"] == "Q-04"]
        for quarantine in q04_rows:
            for holder in external_string_holders(name):
                label = f"{holder}-so-{name}"
                story_specs.append((label, story_text(
                    f"Rewrite {holder} so {name} can be removed", [name], tests,
                    int(parse_int(catalog_by_name[name]["countedCharacters"], field=f"{name} countedCharacters")),
                    None,
                    f"{story_kind_wording[quarantine_story_kind[(name, quarantine['rule'])]]} "
                    f"({quarantine['rule']}): {quarantine['evidence']}",
                    f"rewrite {holder} to remove its string reference to {name}; deletion remains "
                    "prohibited until that rewrite is deployed",
                    [f"string-reference holder {holder}"],
                )))
        other_rewrite_rows = [row for row in rewrite_rows if row["rule"] != "Q-04"]
        if other_rewrite_rows:
            rules_text = "; ".join(
                f"{story_kind_wording[quarantine_story_kind[(name, row['rule'])]]} ({row['rule']}): {row['evidence']}"
                for row in other_rewrite_rows
            )
            label = f"{name}-so-{name}"
            story_specs.append((label, story_text(
                f"Rewrite {name} so {name} can be removed", [name], tests,
                int(parse_int(catalog_by_name[name]["countedCharacters"], field=f"{name} countedCharacters")),
                None, f"Review requirements: {rules_text}",
                f"remove the externally callable, dynamic, or lifecycle surface on {name} before deletion", ["quarantine rewrite"],
            )))
    for story_path in args.stories_dir.glob("*.md"):
        if story_path.is_file() and PLANNER_STORY_MARKER in story_path.read_text(
            encoding="utf-8"
        )[:256]:
            story_path.unlink()
    for number, (label, content) in enumerate(story_specs, start=1):
        (args.stories_dir / f"{number:02d}-{safe_filename(label)}.md").write_text(content, encoding="utf-8")

    final_report = args.out_dir.parent.parent / "report" / "final-report.md"
    blind_spot_lines = []
    for name, value in sorted((blind_spots or {}).items()):
        detail = render_blind_spot_value(value)
        blind_spot_lines.append(f"| {BLIND_SPOT_DISPLAY_NAMES.get(name, name)} | {detail} |")
    targeted_string_lines = [
        f"- {targeted_string_result(name)}"
        for name in sorted(confirmed | requested_annotate)
    ] if args.string_holders else []
    tranche_lines = []
    for tranche in tranche_output:
        unit_names = ", ".join(str(unit["unit"]) for unit in tranche["units"])
        characters = sum(int(unit["countedCharacters"]) for unit in tranche["units"])
        tranche_lines.append(
            f"| {tranche['tranche']} | {unit_names} | {characters} |"
        )
    quarantine_lines = [
        f"| {row['qualifiedName']} | {row['rule']} | {row['evidence']} |"
        for row in quarantine_rows
    ]
    quarantine_footnote = (
        "\n\n*" + FLOW_RULE_UNEVALUATED + ". Affected units: "
        + ", ".join(unevaluated_flow_units) + ".*"
        if unevaluated_flow_units else ""
    )
    disposition_counts = {
        value: sum(row["disposition"] == value for row in dispositions)
        for value in ("remove", "keep", "decide-later", "annotate")
    }
    decide_later = [
        row for row in dispositions if row["disposition"] == "decide-later"
    ]
    deferred_path = args.candidates.parent.parent / "triage" / "deferred.csv"
    if deferred_path.is_file():
        _, deferred_rows = read_csv(deferred_path, required=["qualifiedName", "status"])
    else:
        deferred_rows = []
    decide_later_lines = []
    for row in sorted(
            decide_later,
            key=lambda row: (row["qualifiedName"].casefold(), row["qualifiedName"]),
    ):
        note = (row["note"] or "none").replace("|", "\\|")
        note = note.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "<br>")
        decide_later_lines.append(f"| {row['qualifiedName']} | {note} |")
    required_characters = triage_summary.get("requiredCharacters")
    target = triage_summary.get("target", {})
    target_wording = (
        str(target.get("wording", "not recorded"))
        if isinstance(target, dict) else "not recorded"
    ).replace("|", "\\|").replace("\n", " ")
    target_outcome = (
        "target_met"
        if isinstance(required_characters, int) and forecast >= required_characters
        else "target_unmet"
        if isinstance(required_characters, int)
        else "not_recorded"
    )
    confirmed_label = (
        "Confirmed characters" if reconciled
        else "Confirmed characters (unreconciled candidate)"
    )
    triage_counts = triage_summary.get("counts", {})
    if not isinstance(triage_counts, dict):
        triage_counts = {}
    by_rule = summary.get("byRule", {})
    if not isinstance(by_rule, dict):
        by_rule = {}
    counted_summary = by_rule.get("COUNTED", {})
    if not isinstance(counted_summary, dict):
        counted_summary = {}
    estate_rows = summary.get("rows", len(catalog))
    counted_rows = counted_summary.get(
        "count", sum(row["countedRule"] == "COUNTED" for row in catalog)
    )
    blocked_unit_lines = [
        f"- {unit['unit']}: {unit['blockedReason']}"
        for unit in blocked_units
    ]
    def precursor_story_line(story: dict[str, object]) -> str:
        removed = [str(name) for name in story["removeReferencesTo"]]
        title_units = (
            removed[0]
            if len(removed) == 1
            else ", ".join(removed[:-1]) + f" and {removed[-1]}"
        )
        return f"- Rewrite {story['class']} so {title_units} can be removed."

    precursor_story_lines = [
        precursor_story_line(story)
        for tranche in tranche_output
        for story in tranche["precursorStories"]
    ]
    quarantine_subsections = "".join(
        f"\n\n### {heading}\n\n" + "\n".join(lines)
        for heading, lines in (
            ("Blocked units", blocked_unit_lines),
            ("Test rewrites", precursor_story_lines),
        )
        if lines
    )
    held_characters = sum(int(unit["countedCharacters"]) for unit in blocked_units)

    def ruled_characters(names: set[str]) -> int:
        return sum(
            parse_int(
                catalog_by_name[name]["countedCharacters"],
                allow_empty=True, field=f"{name} countedCharacters",
            ) or 0
            for name in names
        )

    quarantined_characters = ruled_characters(quarantined)
    ruled_remove_characters = ruled_characters(confirmed)
    invariant_lines = []
    for invariant in invariants:
        evidence = []
        for counterexample in invariant["counterexamples"]:
            if "unit" in counterexample and "blockedReason" in counterexample:
                evidence.append(
                    f"{counterexample['unit']}: {counterexample['blockedReason']}"
                )
            else:
                evidence.append(json.dumps(counterexample, sort_keys=True))
        rendered_evidence = "; ".join(evidence).replace("|", "\\|") or "none"
        invariant_lines.append(
            f"| {invariant['name']} | {'passed' if invariant['passed'] else 'failed'} | "
            f"{rendered_evidence} |"
        )
    final_report_text = f"""# Removal plan

## Telemetry window

| Fact | Value |
| --- | ---: |
| Window start | {telemetry_ledger.get('windowStart', 'unknown')} |
| Window end | {telemetry_ledger.get('windowEnd', 'unknown')} |
| Effective days | {telemetry_ledger.get('effectiveDays', 'unknown')} |

## Estate, candidates and rulings

| Fact | Count |
| --- | ---: |
| Components in catalog | {estate_rows} |
| Counted components | {counted_rows} |
| Candidates in bundle | {len(candidates)} |
| Remove rulings | {disposition_counts['remove']} |
| Keep rulings | {disposition_counts['keep']} |
| Decide-later rulings | {disposition_counts['decide-later']} |
| Annotate rulings | {disposition_counts['annotate']} |

## Capacity totals

| Total | Characters |
| --- | ---: |
| Forecast reconciled | {capacity_totals['forecastReconciled']} |
| Unreconciled candidate | {capacity_totals['unreconciledCandidate']} |
| Annotation forecast | {capacity_totals['annotationForecast']} |
| Confirmed realized | blank until deployment |

## Capacity target

| Fact | Value |
| --- | ---: |
| Target | {target_wording} |
| Required characters | {required_characters if isinstance(required_characters, int) else 'not recorded'} |
| Ruled remove characters | {ruled_remove_characters} |
| Placed removals | {deletion_forecast} |
| Held in blocked units | {held_characters} |
| Held in quarantine | {quarantined_characters} |
| Annotate rulings | {annotation_forecast} |
| {confirmed_label} | {forecast} |
| Outcome | {target_outcome} |
| Pre-review selected candidates | {triage_counts.get('selected', 'not recorded')} |
| Pre-review deferred candidates | {triage_counts.get('deferred', 'not recorded')} |
| Pre-review found-in-use candidates | {triage_counts.get('inUse', 'not recorded')} |
| Pre-review kept-use-unknown candidates | {triage_counts.get('keptUseUnknown', 'not recorded')} |
| Post-review remove rulings | {disposition_counts['remove']} |
| Post-review annotate rulings | {disposition_counts['annotate']} |
| Post-review keep rulings | {disposition_counts['keep']} |
| Post-review decide-later rulings | {disposition_counts['decide-later']} |

Ruled remove characters are the placed removals plus the characters held in blocked units and held in quarantine; confirmed characters are the placed removals plus the annotate rulings.

## Tranches

| Tranche | Units | Counted characters |
| ---: | --- | ---: |
{chr(10).join(tranche_lines) if tranche_lines else '| none | none | 0 |'}

## Quarantine

| Class | Rule | Evidence |
| --- | --- | --- |
{chr(10).join(quarantine_lines) if quarantine_lines else '| none | none | none |'}
{quarantine_footnote}{quarantine_subsections}

## Decide-later rulings

| Class | Reviewer note |
| --- | --- |
{chr(10).join(decide_later_lines) if decide_later_lines else '| none | none |'}

## Not reviewed this round

{len(deferred_rows)} {'row' if len(deferred_rows) == 1 else 'rows'} in `work/triage/deferred.csv` were not reviewed this round.

## Blind spots

| Blind spot | Detail |
| --- | --- |
{chr(10).join(blind_spot_lines) if blind_spot_lines else '| unavailable | blind-spots.json was not present |'}

{chr(10).join(targeted_string_lines)}

## Validation

Status: {validation['status']}.

| Invariant | Result | Counterexamples |
| --- | --- | --- |
{chr(10).join(invariant_lines)}

## Release gate

Run a validate-only deployment of the exact manifest with `RunLocalTests`; roll back on any error and do not use ignore-errors.
A later metadata change invalidates this validation.
A failing tranche returns to planning and is not shrunk ad hoc.
"""
    final_report.parent.mkdir(parents=True, exist_ok=True)
    final_report.write_text(final_report_text, encoding="utf-8")
    validation["counts"]["stories"] = len(story_specs)
    validation["counts"]["deletionStories"] = sum(
        content.startswith("# Remove ") for _, content in story_specs
    )
    validation["counts"]["precursorStories"] = sum(
        content.startswith("# Rewrite ") for _, content in story_specs
    )
    validation["counts"]["annotationStories"] = sum(
        content.startswith("# Annotate ") for _, content in story_specs
    )
    write_json(validation_path, validation)
    if unevaluated_flow_units:
        print(
            FLOW_RULE_UNEVALUATED + ": " + ", ".join(unevaluated_flow_units),
            file=sys.stderr,
        )


def main() -> int:
    args = build_parser().parse_args()
    return cli_guard(lambda: run(args))


if __name__ == "__main__":
    sys.exit(main())
